---
title: "Gov 50 Final Project"
author: "Kiersten Hash"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---

## Project thoughts

For my final project, I now plan to analyze nonviolent and violent political movements to assess the relative success of movements that are fought for self-determination, regime changes, or secession.

```{r}
library(tidyverse)
library(dplyr)
navco <- read_csv("NAVCO 1.3 List Final Project.csv")

view(navco)
```
Project Proposal: My research question is "Which types nonviolent and violent political movements are most successful - movements for self determination, regime change, or secession?" I would argue potentially that fights for self determination have probably been the most successful because we saw a global phenomenon of decolonization in the latter half of the 20th century, when many countries were under colonial rule. My explanatory variables will be the types of movements coming from the variables FSELFDET, REGCHANGE, and SECESSION. According to the NAVCO 1.3 codebook, FSELFDET means "1=selfdetermination or independence from a foreign occupier or colonial power, 0=otherwise." REGCHANGE means "1=removal of incumbent national leader, 0=otherwise." SECESSION means "1=territorial secession/separatism from an existing state in a territory internationally recognized as part of the target state, 0=otherwise." The outcome variable is the SUCCESS, LIMITED, and FAILURE variables which measure the extent to which the movement achieved its goals and demands within a year of the movement's "peak activity." In order to support my hypothesis, the data would demonstrate a higher average rate of success for the movements under FSELFDET in comparison to those in the other two groups. The data would not support my hypothesis if one of the other groups had a higher success rate.
